{% set import_path = "github.com/etcd-io/zetcd" %}
{% set version = "0.0.5" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('gopath/src/'+import_path)
  .replace('etcd-io', 'coreos').replace("/", "\\" if win else "/") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    git_url: https://{{ import_path }}
    git_tag: v{{ version }}

build:
  number: 1
  script:
    - pushd {{ pkg_src }}
    - go install -v
        -ldflags "-w -X {{import_path}}/version.Version={{ version }} 
                     -X {{import_path}}/version.SHA={{ GIT_FULL_HASH }}"
        ./cmd/...

requirements:
  build:
    - {{ compiler("go") }}

test:
  commands:
      - which zetcd  # [not win]
      - where zetcd  # [win]
      - zkctl --help
      - zkboom --help

about:
  home: https://github.com/etcd-io/zetcd
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: 'A ZooKeeper "personality" for etcd.'
  description: |
    Zetcd allows serving the Apache Zookeeper API backed with an etcd cluster.

extra:
  recipe-maintainers:
    - adbeda
    - rluria14
    - oblute
    - ndmaxar
