travis:
  secure:
    BINSTAR_TOKEN: mqF3B4oAkEyDyPEO1Vco4gfGGX9sW6DeG2wqKicgUeRGwk3q8YRosXAgWHLw2q/FKJxsaCLrTzsxbiXSmXw+0wNDlFpiEc07S22Qn/VAAjsKJrDqdLQ7u5i6hE7iTR1ifvGin9MWIvp+kZ4uqP834jKnsmVd428U+XohVHnkOfwNS0ruJx8rscLugLJw17hhyFWaVUrOEGgmoPA6LWAW6MFrGa/lGLHRohcAhKQd5L/jDiEwR7ihnx0M4MH2IsczlNGhcZcCch7pYMOQNYaBVTfo7lp9Rnufo5QCjeQ8e9h/wMm1OGpy8Mku9hPAOV6CqLG1PWOdPb6VoHZqWOAY7RsYKtgrlaNaZs4JiZO6gOyjb0Sfn0EB/mQupZWO9KQA1jtNCaFI6qNojgu2M2T4YyhCvj4xHZ2DnXrkR//530HbFyUg0k1vsVV8aiHWq0DU3Hc+91kuQIFy1sjMNduh1/u4Fhdn9FipwFTBUMXZCjDTfX8ENCzE9CyepJW1v9jASopF5fzObBE7CrZvV0p+w3sPHjBqSDH7lMZeKaDfncXuJmJcevzVr8DTlDl5iMp/W6NlJ9wtIRf0vJrczMYdSLlG3qiIeqnynaiKYQV1DprDGzVT+2z74qSj2Ql710t1jDkKKt6cQ9apgv+drEv1v8TVwuJvRYCMttilsLs61f4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
